### ISSUE TITLE
Module not usable

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-lgtv-display#1]
Configured TV/module per instructions; module throws the following error in Companion log:
![image](https://user-images.githubusercontent.com/8798041/170369092-1bffa631-3fb5-4708-bebc-2cf8e2ca3aaf.png)

Module status stays "Connecting" and TV does not respond to power on/off commands from Companion.

**Comment by llamafilm** [comment]
Can you try again with the current version?  It's working fine for me.
